### ISSUE TITLE
Error:BUILD FAILED——Java returned: 1

### ISSUE THREAD

**Issue by xiangkeyu** [utopia-group/apposcopy#3]
JDK1.8,ANT and SDK are all configured,when I run the command‘./stamp analyze adrd/09b143b430e836c513279c0209b7229a4d29a18c.apk’,
a error was throwed out,like this:

Buildfile: /home/yu/Desktop/apposcopy-master/ant/stamp.xml

analyze:
    [mkdir] Created dir: /home/yu/Desktop/apposcopy-master/stamp_output/_home_yu_Desktop_apposcopy-master_adrd_09b143b430e836c513279c0209b7229a4d29a18c.apk
    [unjar] Expanding: /home/yu/Desktop/apposcopy-master/bin/api-16/stamp.android.jar into /home/yu/Desktop/apposcopy-master/stamp_output/_home_yu_Desktop_apposcopy-master_adrd_09b143b430e836c513279c0209b7229a4d29a18c.apk

-analyze-apk:
     [java] I: Copying raw classes.dex file...
     [java] I: Loading resource table...
     [java] I: Loaded.
     [java] I: Decoding AndroidManifest.xml with resources...
     [java] I: Loading resource table from file: /home/yu/Desktop/apposcopy-master/1.apk
     [java] I: Loaded.
     [java] I: Regular manifest package...
     [java] I: Decoding file-resources...
     [java] I: Decoding values */* XMLs...
     [java] I: Done.
     [java] I: Copying assets and libs...
     [java] Warning: java.lang.ref.Finalizer is a phantom class!
     [java] Component: com.xxx.yyy.MyBoolService
     [java] Component: com.ophone.MiniPlayer.LogoActivity
     [java] Component: com.ophone.MiniPlayer.MusicActivity
     [java] Component: com.xxx.yyy.MyService
     [java] Component: com.ophone.MiniPlayer.MusicFeedActivity
     [java] Component: com.ophone.MiniPlayer.OnlineMusicActivity
     [java] Component: com.ophone.MiniPlayer.MyPlayerService
     [java] Component: com.ophone.MiniPlayer.MyPlayer
     [java] Component: com.xxx.yyy.MyAlarmReceiver
     [java] Component: com.ophone.MiniPlayer.MainActivity
     [java] Component: com.ophone.MiniPlayer.Search
     [java] Component: com.ophone.MiniPlayer.PlayingListActivity
     [java] Component: com.ophone.MiniPlayer.lyricsactivity
     [java] Custom GUI: com.ophone.MiniPlayer.MyView
     [echo] Using default value "chord" for property stamp.backend (backend to use for analyzing the app [chord,solvergen])

-prepare-backend-chord:
     [java] Redirecting stdout to file: /home/yu/Desktop/apposcopy-master/stamp_output/_home_yu_Desktop_apposcopy-master_adrd_09b143b430e836c513279c0209b7229a4d29a18c.apk/chord_output/log.txt
     [java] Redirecting stderr to file: /home/yu/Desktop/apposcopy-master/stamp_output/_home_yu_Desktop_apposcopy-master_adrd_09b143b430e836c513279c0209b7229a4d29a18c.apk/chord_output/log.txt

BUILD FAILED
/home/yu/Desktop/apposcopy-master/ant/apptasks.xml:38: The following error occurred while executing this line:
/home/yu/Desktop/apposcopy-master/ant/apptasks_dex.xml:93: Java returned: 1

Total time: 2 minutes 37 seconds

And I opened the file--apptasks_dex.xml:93,'<java classname="shord.project.Boot" fork="true" failonerror="true">'.
'shord' maybe 'chord'?
Then I changed it,ran this command again，while the error was still existing and the 'Total time' reduced to 8 seconds.

So could you help me solve this problem?
Thanks！

**Comment by JunTomyang** [comment]
@xiangkeyu  Hi, have you solved this problem? I came across with the same error with you.

**Comment by SelmiSaiida** [comment]
me too , please tell me what should i do !!!
